export const dateFilterTabs = [
  'TODOS',
  'TRANSFERIDO',
  'NIECA CONFIRMACION DATOS',
  'CLIENTE NO ENCONTRADO EN DB',
  'LLAMANDO',
  'CORTO CLIENTE',
  'MAIL ENVIADO',
  'INDEFINIDO',
  'NO ENCONTRADO EN DB',
];
